export const PRELOADED_TASBIH = [
  {
    name: 'SubhanAllah',
    arabicText: 'سُبْحَانَ اللَّهِ',
    translation: 'Glory be to Allah',
    category: 'Tasbih',
    tags: ['morning', 'evening', 'general'],
    defaultTarget: 33,
    targetType: 'session' as const,
    isPreloaded: true,
    sortOrder: 1,
  },
  {
    name: 'Alhamdulillah',
    arabicText: 'الْحَمْدُ لِلَّهِ',
    translation: 'All praise is due to Allah',
    category: 'Tahmid',
    tags: ['morning', 'evening', 'general'],
    defaultTarget: 33,
    targetType: 'session' as const,
    isPreloaded: true,
    sortOrder: 2,
  },
  {
    name: 'Allahu Akbar',
    arabicText: 'اللَّهُ أَكْبَرُ',
    translation: 'Allah is the Greatest',
    category: 'Takbir',
    tags: ['morning', 'evening', 'general'],
    defaultTarget: 34,
    targetType: 'session' as const,
    isPreloaded: true,
    sortOrder: 3,
  },
  {
    name: 'Durood Ibrahim',
    arabicText: 'اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ',
    translation: 'O Allah, send blessings upon Muhammad',
    category: 'Durood',
    tags: ['morning', 'evening', 'friday'],
    defaultTarget: 100,
    targetType: 'daily' as const,
    isPreloaded: true,
    sortOrder: 4,
  },
  {
    name: 'Istighfar',
    arabicText: 'أَسْتَغْفِرُ اللَّهَ',
    translation: 'I seek forgiveness from Allah',
    category: 'Istighfar',
    tags: ['morning', 'evening', 'general'],
    defaultTarget: 100,
    targetType: 'daily' as const,
    isPreloaded: true,
    sortOrder: 5,
  },
];

export const PROFILE_COLORS = [
  '#1a5c38', '#2d9e6b', '#c9a227', '#1a4a5c',
  '#5c1a38', '#3d5c1a', '#5c3d1a', '#1a1a5c',
];
